#!/bin/bash

set -e

echo "Installing Composer dependencies..."
composer install --prefer-dist --no-interaction

echo "Initializing database..."
php bin/console doctrine:database:drop --force --if-exists
php bin/console doctrine:database:create

echo "Applying migrations..."
php bin/console doctrine:migrations:migrate --no-interaction

echo "Running synchronization..."
php bin/console app:sync-popular-movies
